### ISSUE TITLE
Default Discord prevents Cosmo from serving album graphic

### ISSUE THREAD

**Issue by jkiernan12** [adamanldo/Cosmo#1]
A user with a generic Discord profile avatar can't set a new account.

## Expected Behavior
As a user with a generic user profile avatar, when I type .fmi  Cosmo should reply with an image of the album and my avatar.

## Current Behavior
Cosmo replies with an error message of 'Something went wrong...I'm not feeling to good...'

## Steps to Reproduce
1. Set your Discord avatar to generic.
2. In your server with Cosmo, type .fmi

**Comment by adamanldo** [comment]
Fixed. My best guess is this is due to Discord changing their default avatar PNG to a palette/colormapped PNG (more info on palette/colormapped images [here](http://www.libpng.org/pub/png/book/chapter08.html)). From what I understand it's just a way to save some memory for PNG images that have less than 256 colors by not storing full RGB data for each pixel.

Cosmo uses the Pillow library to create the final fmi, and at a certain point it needs to mask the avatar in the bottom right inside the triangle. Pillow cannot use an image in palette mode to do this, so this was fixed by just converting all avatars to RGB mode explicitly to be safe.

02d0a9a38063874501970275d84afa251e86ccc3
